server:
  port: 8080
  servlet:
    context-path: /springboot

girl:
  name: baby
  age: 18
  content: content:${name},age:${age}

spring:
  profiles:
    active: prod

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: sunyan589

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.ocean.pojo

jpa:
  hibernate:
   ddl-auto: create
    show-sql: true
